# Utility Script - SGF Format Properties in a dictionary format
from datatime import datetime

PROPS = {'AB': {'data_type': <class 'list'>,
        'desc': 'Add Black',
        'full_desc': 'Add black setup or handicap stones, e.g., AB[dp][pd]',
        'prop': 'AB'},
 'AE': {'data_type': <class 'list'>,
        'desc': 'Add Empty',
        'full_desc': 'Make the indicated fields empty',
        'prop': 'AE'},
 'AN': {'data_type': <class 'str'>,
        'desc': 'Annotator',
        'full_desc': 'Author of the game analysis',
        'prop': 'AN'},
 'AP': {'data_type': <class 'str'>,
        'desc': 'Application',
        'full_desc': 'SGF editor used',
        'prop': 'AP'},
 'AW': {'data_type': <class 'list'>,
        'desc': 'Add White',
        'full_desc': 'Add white stones',
        'prop': 'AW'},
 'B': {'data_type': <class 'tuple'>,
       'desc': 'Black move',
       'full_desc': 'Make a black move',
       'prop': 'B'},
 'BC': {'data_type': <class 'str'>,
        'desc': 'Black Country',
        'full_desc': 'Country of the black player, e.g. CN, JP, KR, TW',
        'prop': 'BC'},
 'BL': {'data_type': <class 'datetime.datetime'>,
        'desc': 'Black time Left',
        'full_desc': 'Time left after this move',
        'prop': 'BL'},
 'BR': {'data_type': <class 'str'>,
        'desc': 'Black Rank',
        'full_desc': 'Rank of black player, e.g. Honorary Meijin, 9p, 6d ama, '
                     '15k',
        'prop': 'BR'},
 'BT': {'data_type': <class 'str'>,
        'desc': 'Black Team',
        'full_desc': 'Team of the black player',
        'prop': 'BT'},
 'C': {'data_type': <class 'str'>,
       'desc': 'Comment',
       'full_desc': 'Any comment',
       'prop': 'C'},
 'CA': {'data_type': <class 'str'>,
        'desc': 'Character set',
        'full_desc': 'Character set of the text fields (e.g., UTF-8, GB2312, '
                     'SJIS, ISO-2022-KR, ISO-8859-15)',
        'prop': 'CA'},
 'CP': {'data_type': <class 'str'>,
        'desc': 'Copyright',
        'full_desc': 'Copyright holder',
        'prop': 'CP'},
 'CR': {'data_type': <class 'list'>,
        'desc': 'Circle',
        'full_desc': 'Mark the indicated stones with a circle',
        'prop': 'CR'},
 'DT': {'data_type': <class 'str'>,
        'desc': 'Date',
        'full_desc': 'Date, given in Western style, preferably in ISO standard '
                     'form',
        'prop': 'DT'},
 'EV': {'data_type': <class 'str'>,
        'desc': 'Event',
        'full_desc': 'Tournament or other event',
        'prop': 'EV'},
 'FF': {'data_type': <class 'int'>,
        'desc': 'File Format',
        'full_desc': 'SGF file format, e.g., FF[1], FF[3], FF[4]',
        'prop': 'FF'},
 'GC': {'data_type': <class 'str'>,
        'desc': 'Game Comment',
        'full_desc': "Any comment. E.g. GC[This is Cho Chikun's 1000th win as "
                     'a professional], GC[Translated by Megumi Kawai], GC[Wang '
                     'Lei made an illegal ko capture on move 223 in what '
                     'should have been a void game due to triple ko. He was '
                     'ruled to have passed on that move and the position was '
                     'restored with Zhou to move]',
        'prop': 'GC'},
 'GM': {'data_type': <class 'int'>,
        'desc': 'Game',
        'full_desc': 'GM[1]: Go. Higher numbers denote other games, see GM',
        'prop': 'GM'},
 'GN': {'data_type': <class 'str'>,
        'desc': 'Game Name',
        'full_desc': 'Filename, number or identifier associated with the game',
        'prop': 'GN'},
 'HA': {'data_type': <class 'int'>,
        'desc': 'Handicap',
        'full_desc': 'Number of handicap stones',
        'prop': 'HA'},
 'JD': {'data_type': <class 'str'>,
        'desc': 'Japanese Date',
        'full_desc': 'Date, given in Japanese Era, Year, Month, Day format',
        'prop': 'JD'},
 'KM': {'data_type': <class 'float'>,
        'desc': 'Komi',
        'full_desc': 'Possibly negative number of points paid by Black to '
                     'White',
        'prop': 'KM'},
 'LB': {'data_type': <class 'list'>,
        'desc': 'Label',
        'full_desc': 'E.g. LB[], LB[kg:a], '
                     'LB[fm:F][fj:E][fk:D][gj:C][gk:B][hi:A]',
        'prop': 'LB'},
 'LC': {'data_type': <class 'int'>,
        'desc': 'Number of Byo-yomi',
        'full_desc': 'Number of byo-yomi periods',
        'prop': 'LC'},
 'LT': {'data_type': <class 'datetime.datetime'>,
        'desc': 'Length Byo-yomi',
        'full_desc': 'Length of byo-yomi periods',
        'prop': 'LT'},
 'MA': {'data_type': <class 'list'>,
        'desc': 'Mark',
        'full_desc': "Mark the indicated stones with an 'X'",
        'prop': 'MA'},
 'MN': {'data_type': <class 'int'>,
        'desc': 'Move Number',
        'full_desc': 'In the rootnode: the number of moves of the game. '
                     'Elsewhere: the request to label the move with the given '
                     'number',
        'prop': 'MN'},
 'N': {'data_type': <class 'str'>,
       'desc': 'Node name',
       'full_desc': 'E.g. N[Diagram 1], N[Sacrifice]',
       'prop': 'N'},
 'OB': {'data_type': <class 'int'>,
        'desc': 'Overtime Black',
        'full_desc': 'Number of black moves still to make in this byo-yomi '
                     'period',
        'prop': 'OB'},
 'OH': {'data_type': <class 'str'>,
        'desc': 'Old Handicap',
        'full_desc': 'E.g. OH[(B)BW] for sen-ai-sen, a handicap where the '
                     'weaker player takes Black two out of every three games, '
                     'and takes Black in the present game',
        'prop': 'OH'},
 'OT': {'data_type': <class 'str'>,
        'desc': 'Overtime',
        'full_desc': 'Description of the type of byo-yomi used',
        'prop': 'OT'},
 'OW': {'data_type': <class 'int'>,
        'desc': 'Overtime White',
        'full_desc': 'Number of white moves still to make in this byo-yomi '
                     'period',
        'prop': 'OW'},
 'PB': {'data_type': <class 'str'>,
        'desc': 'Player Black',
        'full_desc': 'Name of black player',
        'prop': 'PB'},
 'PC': {'data_type': <class 'str'>,
        'desc': 'Place',
        'full_desc': 'Location of the game',
        'prop': 'PC'},
 'PL': {'data_type': <class 'str'>,
        'desc': 'Player to play',
        'full_desc': 'Player to go first (B or W)',
        'prop': 'PL'},
 'PW': {'data_type': <class 'str'>,
        'desc': 'Player White',
        'full_desc': 'Name of white player',
        'prop': 'PW'},
 'RE': {'data_type': <class 'str'>,
        'desc': 'Result',
        'full_desc': 'E.g. Jigo, B+3.5, W+T, Void. See RE',
        'prop': 'RE'},
 'RO': {'data_type': <class 'str'>,
        'desc': 'Round',
        'full_desc': 'Tournament stage or round',
        'prop': 'RO'},
 'RU': {'data_type': <class 'str'>,
        'desc': 'Rules',
        'full_desc': 'Rule set in use',
        'prop': 'RU'},
 'SL': {'data_type': <class 'list'>,
        'desc': 'Selected points',
        'full_desc': 'Select a number of points in order to refer to them in a '
                     'comment',
        'prop': 'SL'},
 'SO': {'data_type': <class 'str'>,
        'desc': 'Source',
        'full_desc': 'Game source. E.g. SO[weiqi.com.tom], SO[Kido yearbook '
                     '1969]',
        'prop': 'SO'},
 'SQ': {'data_type': <class 'list'>,
        'desc': 'Square',
        'full_desc': 'Mark the indicated stones with a square',
        'prop': 'SQ'},
 'SZ': {'data_type': <class 'int'>,
        'desc': 'Size',
        'full_desc': 'E.g. SZ[19], or SZ[2:9] for a 2x9 board (with 2 columns '
                     'and 9 rows)',
        'prop': 'SZ'},
 'TB': {'data_type': <class 'list'>,
        'desc': 'Territory Black',
        'full_desc': 'Black territory',
        'prop': 'TB'},
 'TM': {'data_type': <class 'datetime.datetime'>,
        'desc': 'Time',
        'full_desc': 'Total time for each player',
        'prop': 'TM'},
 'TR': {'data_type': <class 'list'>,
        'desc': 'Triangle',
        'full_desc': 'Mark the indicated stones with a triangle',
        'prop': 'TR'},
 'TW': {'data_type': <class 'list'>,
        'desc': 'Territory White',
        'full_desc': 'White territory',
        'prop': 'TW'},
 'US': {'data_type': <class 'str'>,
        'desc': 'User',
        'full_desc': 'User who entered the game',
        'prop': 'US'},
 'VW': {'data_type': <class 'list'>,
        'desc': 'View',
        'full_desc': 'Part of the board to be shown. A subsequent VW[] removes '
                     'this restriction',
        'prop': 'VW'},
 'W': {'data_type': <class 'tuple'>,
       'desc': 'White move',
       'full_desc': 'Make a white move',
       'prop': 'W'},
 'WC': {'data_type': <class 'str'>,
        'desc': 'White Country',
        'full_desc': 'Country of the white player',
        'prop': 'WC'},
 'WL': {'data_type': <class 'datetime.datetime'>,
        'desc': 'White time Left',
        'full_desc': 'Time left after this move',
        'prop': 'WL'},
 'WR': {'data_type': <class 'str'>,
        'desc': 'White Rank',
        'full_desc': 'Rank of white player',
        'prop': 'WR'},
 'WT': {'data_type': <class 'str'>,
        'desc': 'White Team',
        'full_desc': 'Team of the white player',
        'prop': 'WT'}}

DESCRIPTIONS = {'Add Black': 'AB',
 'Add Empty': 'AE',
 'Add White': 'AW',
 'Annotator': 'AN',
 'Application': 'AP',
 'Black Country': 'BC',
 'Black Rank': 'BR',
 'Black Team': 'BT',
 'Black move': 'B',
 'Black time Left': 'BL',
 'Character set': 'CA',
 'Circle': 'CR',
 'Comment': 'C',
 'Copyright': 'CP',
 'Date': 'DT',
 'Event': 'EV',
 'File Format': 'FF',
 'Game': 'GM',
 'Game Comment': 'GC',
 'Game Name': 'GN',
 'Handicap': 'HA',
 'Japanese Date': 'JD',
 'Komi': 'KM',
 'Label': 'LB',
 'Length Byo-yomi': 'LT',
 'Mark': 'MA',
 'Move Number': 'MN',
 'Node name': 'N',
 'Number of Byo-yomi': 'LC',
 'Old Handicap': 'OH',
 'Overtime': 'OT',
 'Overtime Black': 'OB',
 'Overtime White': 'OW',
 'Place': 'PC',
 'Player Black': 'PB',
 'Player White': 'PW',
 'Player to play': 'PL',
 'Result': 'RE',
 'Round': 'RO',
 'Rules': 'RU',
 'Selected points': 'SL',
 'Size': 'SZ',
 'Source': 'SO',
 'Square': 'SQ',
 'Territory Black': 'TB',
 'Territory White': 'TW',
 'Time': 'TM',
 'Triangle': 'TR',
 'User': 'US',
 'View': 'VW',
 'White Country': 'WC',
 'White Rank': 'WR',
 'White Team': 'WT',
 'White move': 'W',
 'White time Left': 'WL'}

 DATA_TYPES = {
 	"simpletext": str,
 	"color": str,
 	"number | numberpair": int,
 	"move": tuple,
 	"number": int,
 	"real": float,
 	"text": str,
 	"time": datetime,
 	"labellist": list,
 	"pointlist": list
 	}